security:
    # Hashowanie haseł
    password_hashers:
        App\Entity\User:
            algorithm: auto
    
    # Dostawca użytkowników
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    # Firewalle
    firewalls:
        # (opcjonalnie) dev tools
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # 🔑 API (JWT) – musi być PRZED "main"
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
        
        # WEB – wykluczamy /api z tego firewalla
        main:
            pattern: ^/(?!api)      # << NIE łapie /api/*
            lazy: true
            provider: app_user_provider
            
            form_login:
                login_path: login
                check_path: login
                username_parameter: _username
                password_parameter: _password
                default_target_path: /mainPage
                always_use_default_target_path: false
            
            logout:
                path: logout
                target: login
    
    # Dostęp
    access_control:
        - { path: ^/api/login,    roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin,    roles: ROLE_ADMIN }
        - { path: ^/api,          roles: IS_AUTHENTICATED_FULLY }
